### ISSUE TITLE
Dealing with TypedResponse<never>

### ISSUE THREAD

**Issue by davemurphysf** [kiliman/remix-typedjson-example#3]
Hi!

I have a loader that will throw if a database call fails.  Because of this, the type returned by `const loaderData = useTypedLoaderData<typeof loader>()` in my route now looks like this:
```
TypedResponse<never> | TypedJsonResponse<{
    // my json
}>
```

Even if I check my `loaderData` for truthiness, the type still stays the same.  The only way I've found to make typescript happy is to use the `as` keyword like so in my route:
```
const data = loaderData as TypedJsonResponse<{
    // my json
}>;
```

This works but feels...wrong.

Am I missing a more elegant solution here?

**Comment by davemurphysf** [comment]
This is a better solution, but still would be interested to know if there is a yet better one:
```
const data = loaderData as Exclude<typeof loaderData, TypedResponse<never>>;
```

**Comment by davemurphysf** [comment]
I'm an idiot; this was due to the types generated from `redirect` not the throwing.  Closing this issue.

**Comment by kiliman** [comment]
Yeah you need to import the redirect from `remix-typedjson` due to the return type.
